name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: get the name from pack.json
        id: props
        shell: bash
        run: echo "name=$(cat pack.json | jq '.name' | tr -d '"')" >> $GITHUB_OUTPUT

      - name: create zip archive
        run: bash ./.github/archive.sh

      - name: Add files to GitHub-Release
        uses: shogo82148/actions-upload-release-asset@v1.7.5
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./${{ steps.props.outputs.name }}-*.zip"
          overwrite: true
